title: Terry Ling
logo: /assets/img/headshot.png
description: "Personal website"
#google_analytics: 
show_download: false
#theme: jekyll-theme-minimal
remote_theme: BDHU/minimalist
color-scheme: auto
#email: terry dot lingyun at gmail dot com
#blank_title: true
sidebar:
  - name: Curriculum Vitae
    icon: <i class="fa-regular fa-file"></i>
    link: /assets/pdf/cv.pdf
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin-in"></i>
    link: https://www.linkedin.com/in/terryyling/
  - name: Email
    icon: <i class="fa-regular fa-envelope"></i>
    link: mailto:terry.lingyun@gmail.com
github: [metadata]
