title: Terry Ling
logo: /assets/img/headshot.png
description: "Personal website"
#google_analytics: 
show_download: false
#theme: jekyll-theme-minimal
remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jemoji
#email: terry dot lingyun at gmail dot com
#blank_title: true
sidebar:
  - name: Curriculum Vitae
    icon: <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zm4 18H6V4h7v5h5z"/></svg>
    link: /assets/pdf/cv.pdf
  - name: LinkedIn
    icon: <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M6.94 5a2 2 0 1 1-4-.002a2 2 0 0 1 4 .002M7 8.48H3V21h4zm6.32 0H9.34V21h3.94v-6.57c0-3.66 4.77-4 4.77 0V21H22v-7.93c0-6.17-7.06-5.94-8.72-2.91z"/></svg>
    link: https://www.linkedin.com/in/terryyling/
  - name: Email
    icon: <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M22 6c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2zm-2 0l-8 5l-8-5zm0 12H4V8l8 5l8-5z"/></svg>
    link: mailto:terry.lingyun@gmail.com
github: [metadata]
